models:
  - name: price_daily_merged
    descrpition: price merged data
    columns:
      - name: ticker
        tests:
          - not_null:
              name: my_not_null_test
              config:
                severity: warn
        descrpition: The date of the price data
    config:
      materialized: view
      tags:
        - price
        - daily

  - name: kospi200_constituents_daily
    tests:
      - dbt_utils.unique_combination_of_columns:          
          combination_of_columns:
            - target_index_name
            - ticker
            - date_kst
      
  - name: price_of_kospi200_daily